import { useState, useEffect, useRef } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { useEmailTemplates, useCreateEmailTemplate } from '@/hooks/useEmailTemplates';
import { useSendEmail } from '@/hooks/useSendEmail';
import { useDocuments } from '@/hooks/useDocuments';
import { supabase } from '@/integrations/supabase/client';
import {
  Send,
  Loader2,
  Sparkles,
  Clock,
  Paperclip,
  X,
  FileText,
  Upload,
  ChevronDown,
  Save,
} from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

interface SmartComposeModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  investorId?: string;
  investorName?: string;
  investorEmail?: string;
  preAttachedDocIds?: string[];
  onEmailSent?: () => void;
}

export function SmartComposeModal({
  open,
  onOpenChange,
  investorId,
  investorName,
  investorEmail,
  preAttachedDocIds,
  onEmailSent,
}: SmartComposeModalProps) {
  const [to, setTo] = useState('');
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [customInstructions, setCustomInstructions] = useState('');
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [scheduledTime, setScheduledTime] = useState('');
  const [attachedDocIds, setAttachedDocIds] = useState<string[]>([]);
  const [manualFiles, setManualFiles] = useState<File[]>([]);
  const [aiReasoning, setAiReasoning] = useState('');
  const [showSchedulePicker, setShowSchedulePicker] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const { data: templates } = useEmailTemplates();
  const createTemplate = useCreateEmailTemplate();
  const sendEmail = useSendEmail();
  const { documents } = useDocuments();

  useEffect(() => {
    if (open) {
      setTo(investorEmail || '');
      setSubject('');
      setBody('');
      setCustomInstructions('');
      setSelectedTemplateId('');
      setScheduledTime('');
      setAttachedDocIds(preAttachedDocIds || []);
      setManualFiles([]);
      setAiReasoning('');
      setShowSchedulePicker(false);
    }
  }, [open, investorEmail]);

  const stripHtml = (text: string) =>
    text
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<\/p>/gi, '\n\n')
      .replace(/<[^>]+>/g, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

  const replacePlaceholders = (text: string) => {
    const firstName = investorName?.split(' ')[0] || '';
    return text
      .replace(/\{\{name\}\}/gi, investorName || '')
      .replace(/\{\{first_name\}\}/gi, firstName)
      .replace(/\{\{investor_name\}\}/gi, investorName || '')
      .replace(/\{\{email\}\}/gi, investorEmail || '');
  };

  const cleanText = (text: string) => replacePlaceholders(stripHtml(text));

  const handleTemplateSelect = (templateId: string) => {
    setSelectedTemplateId(templateId);
    const template = templates?.find((t) => t.id === templateId);
    if (template) {
      setSubject(replacePlaceholders(template.subject));
      setBody(cleanText(template.body));
    }
  };

  const handleGenerateWithAI = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-email', {
        body: {
          investorId,
          templateId: selectedTemplateId || undefined,
          customInstructions: customInstructions || undefined,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setSubject(replacePlaceholders(data.subject || subject));
      setBody(cleanText(data.body || body));
      setAiReasoning(data.reasoning || '');

      if (data.suggested_documents?.length > 0) {
        const validIds = data.suggested_documents.filter((id: string) =>
          documents.some((d) => d.id === id)
        );
        setAttachedDocIds((prev) => [...new Set([...prev, ...validIds])]);
      }

      toast.success('Email generated by AI');
    } catch (error) {
      console.error('AI generation error:', error);
      toast.error('Failed to generate email', {
        description: error instanceof Error ? error.message : 'Please try again',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleAttachment = (docId: string) => {
    setAttachedDocIds((prev) =>
      prev.includes(docId) ? prev.filter((id) => id !== docId) : [...prev, docId]
    );
  };

  const handleSend = async () => {
    if (!to || !subject || !body) {
      toast.error('Please fill in all required fields');
      return;
    }

    if (scheduledTime) {
      toast.info('Email scheduled', {
        description: `Will be sent at ${format(new Date(scheduledTime), 'MMM d, yyyy h:mm a')}`,
      });
    }

    await sendEmail.mutateAsync({
      to,
      subject,
      body,
      attachment_doc_ids: attachedDocIds.length > 0 ? attachedDocIds : undefined,
    });
    onEmailSent?.();
    onOpenChange(false);
  };

  const handleSaveAsTemplate = () => {
    if (!subject && !body) {
      toast.error('Write an email first before saving as template');
      return;
    }
    const templateName = investorName
      ? `Email to ${investorName} - ${new Date().toLocaleDateString()}`
      : `Email Template - ${new Date().toLocaleDateString()}`;

    createTemplate.mutate({
      name: templateName,
      subject,
      body,
      category: 'outreach',
    });
  };

  const attachedDocs = documents.filter((d) => attachedDocIds.includes(d.id));

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] flex flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary" />
            Smart Compose
            {investorName && (
              <Badge variant="secondary" className="ml-2 font-normal">
                {investorName}
              </Badge>
            )}
          </DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto pr-1 space-y-4 pb-2">
          {/* AI Generation Section */}
          <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 space-y-3">
            <p className="text-sm font-medium flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-primary" />
              AI Email Generation
            </p>

            {templates && templates.length > 0 && (
              <div>
                <Label className="text-xs text-muted-foreground">Base Template (optional)</Label>
                <Select value={selectedTemplateId} onValueChange={handleTemplateSelect}>
                  <SelectTrigger className="mt-1">
                    <SelectValue placeholder="Select a template..." />
                  </SelectTrigger>
                  <SelectContent>
                    {templates.map((t) => (
                      <SelectItem key={t.id} value={t.id}>
                        {t.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            <div>
              <Label className="text-xs text-muted-foreground">
                Custom Instructions (optional)
              </Label>
              <Input
                placeholder="e.g., Focus on our Q4 traction, mention our SBA experience..."
                value={customInstructions}
                onChange={(e) => setCustomInstructions(e.target.value)}
                className="mt-1"
              />
            </div>

            <Button
              onClick={handleGenerateWithAI}
              disabled={isGenerating}
              className="w-full"
              variant="outline"
            >
              {isGenerating ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4 mr-2" />
              )}
              {isGenerating ? 'Generating...' : 'Generate with AI'}
            </Button>

            {aiReasoning && (
              <p className="text-xs text-muted-foreground italic border-l-2 border-primary/30 pl-2">
                {aiReasoning}
              </p>
            )}
          </div>

          {/* Email Fields */}
          <div>
            <Label htmlFor="to">To</Label>
            <Input
              id="to"
              type="email"
              placeholder="recipient@example.com"
              value={to}
              onChange={(e) => setTo(e.target.value)}
            />
          </div>

          <div>
            <Label htmlFor="subject">Subject</Label>
            <Input
              id="subject"
              placeholder="Email subject"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
            />
          </div>

          <div>
            <Label htmlFor="body">Message</Label>
            <Textarea
              id="body"
              placeholder="Write your message or generate with AI..."
              className="min-h-[150px]"
              value={body}
              onChange={(e) => setBody(e.target.value)}
            />
          </div>

          {/* Attachments - compact */}
          <div>
            <div className="flex items-center justify-between">
              <Label className="flex items-center gap-2">
                <Paperclip className="w-4 h-4" />
                Attachments
              </Label>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => fileInputRef.current?.click()}
                className="gap-1 h-7 text-xs"
              >
                <Upload className="w-3 h-3" />
                Upload
              </Button>
              <input
                ref={fileInputRef}
                type="file"
                multiple
                className="hidden"
                onChange={(e) => {
                  if (e.target.files) {
                    setManualFiles((prev) => [...prev, ...Array.from(e.target.files!)]);
                  }
                  e.target.value = '';
                }}
              />
            </div>

            {(attachedDocs.length > 0 || manualFiles.length > 0) && (
              <div className="flex flex-wrap gap-1.5 mt-2">
                {attachedDocs.map((doc) => (
                  <Badge key={doc.id} variant="secondary" className="flex items-center gap-1 pr-1 text-xs">
                    <FileText className="w-3 h-3" />
                    <span className="max-w-[120px] truncate">{doc.name}</span>
                    <button onClick={() => toggleAttachment(doc.id)} className="ml-1 hover:text-destructive">
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
                {manualFiles.map((file, idx) => (
                  <Badge key={`manual-${idx}`} variant="secondary" className="flex items-center gap-1 pr-1 text-xs">
                    <Upload className="w-3 h-3" />
                    <span className="max-w-[120px] truncate">{file.name}</span>
                    <button onClick={() => setManualFiles((prev) => prev.filter((_, i) => i !== idx))} className="ml-1 hover:text-destructive">
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
              </div>
            )}

            {documents.length > 0 && (
              <div className="mt-2 max-h-[100px] overflow-y-auto border rounded-md">
                {documents
                  .filter((d) => !attachedDocIds.includes(d.id))
                  .map((doc) => (
                    <button
                      key={doc.id}
                      onClick={() => toggleAttachment(doc.id)}
                      className="w-full text-left px-3 py-1.5 text-xs hover:bg-accent/50 flex items-center gap-2 border-b last:border-b-0"
                    >
                      <FileText className="w-3 h-3 text-muted-foreground shrink-0" />
                      <span className="truncate">{doc.name}</span>
                      <Badge variant="outline" className="text-[10px] ml-auto shrink-0">
                        {doc.document_type}
                      </Badge>
                    </button>
                  ))}
              </div>
            )}
          </div>

          {/* Schedule picker (shown conditionally) */}
          {showSchedulePicker && (
            <div className="rounded-lg border p-3 space-y-2">
              <Label className="text-xs text-muted-foreground">Schedule send time</Label>
              <Input
                type="datetime-local"
                value={scheduledTime}
                onChange={(e) => setScheduledTime(e.target.value)}
                min={format(new Date(), "yyyy-MM-dd'T'HH:mm")}
              />
              {scheduledTime && (
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="text-xs">
                    <Clock className="w-3 h-3 mr-1" />
                    {format(new Date(scheduledTime), 'MMM d, yyyy h:mm a')}
                  </Badge>
                  <button onClick={() => { setScheduledTime(''); setShowSchedulePicker(false); }} className="text-muted-foreground hover:text-foreground">
                    <X className="w-3 h-3" />
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Actions - fixed at bottom */}
        <div className="flex items-center justify-between pt-3 border-t">
          <Button
            variant="ghost"
            size="sm"
            onClick={handleSaveAsTemplate}
            disabled={(!subject && !body) || createTemplate.isPending}
            className="gap-1 text-xs text-muted-foreground"
          >
            {createTemplate.isPending ? <Loader2 className="w-3 h-3 animate-spin" /> : <Save className="w-3 h-3" />}
            Save as Template
          </Button>

          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>

            {/* Send with dropdown for schedule */}
            <div className="flex items-center">
              <Button
                onClick={handleSend}
                disabled={!to || !subject || !body || sendEmail.isPending}
                className="rounded-r-none"
                size="sm"
              >
                {sendEmail.isPending ? (
                  <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                ) : scheduledTime ? (
                  <Clock className="w-4 h-4 mr-1" />
                ) : (
                  <Send className="w-4 h-4 mr-1" />
                )}
                {scheduledTime ? 'Schedule' : 'Send'}
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    size="sm"
                    className="rounded-l-none border-l border-primary-foreground/20 px-2"
                    disabled={!to || !subject || !body || sendEmail.isPending}
                  >
                    <ChevronDown className="w-3.5 h-3.5" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="bg-popover">
                  <DropdownMenuItem onClick={() => { setScheduledTime(''); setShowSchedulePicker(false); }}>
                    <Send className="w-4 h-4 mr-2" />
                    Send Now
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => setShowSchedulePicker(true)}>
                    <Clock className="w-4 h-4 mr-2" />
                    Schedule Send
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
