import { useState, useEffect, useRef } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useEmailTemplates } from '@/hooks/useEmailTemplates';
import { useSendEmail } from '@/hooks/useSendEmail';
import { useDocuments } from '@/hooks/useDocuments';
import { supabase } from '@/integrations/supabase/client';
import {
  Send,
  Loader2,
  Sparkles,
  Clock,
  Paperclip,
  X,
  FileText,
  CalendarClock,
  Upload,
} from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

interface SmartComposeModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  investorId?: string;
  investorName?: string;
  investorEmail?: string;
}

export function SmartComposeModal({
  open,
  onOpenChange,
  investorId,
  investorName,
  investorEmail,
}: SmartComposeModalProps) {
  const [to, setTo] = useState('');
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [customInstructions, setCustomInstructions] = useState('');
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [scheduledTime, setScheduledTime] = useState('');
  const [attachedDocIds, setAttachedDocIds] = useState<string[]>([]);
  const [manualFiles, setManualFiles] = useState<File[]>([]);
  const [aiReasoning, setAiReasoning] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const { data: templates } = useEmailTemplates();
  const sendEmail = useSendEmail();
  const { documents } = useDocuments();

  // Reset form when opening with investor context
  useEffect(() => {
    if (open) {
      setTo(investorEmail || '');
      setSubject('');
      setBody('');
      setCustomInstructions('');
      setSelectedTemplateId('');
      setScheduledTime('');
      setAttachedDocIds([]);
      setManualFiles([]);
      setAiReasoning('');
    }
  }, [open, investorEmail]);

  const stripHtml = (text: string) =>
    text
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<\/p>/gi, '\n\n')
      .replace(/<[^>]+>/g, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

  const replacePlaceholders = (text: string) => {
    const firstName = investorName?.split(' ')[0] || '';
    return text
      .replace(/\{\{name\}\}/gi, investorName || '')
      .replace(/\{\{first_name\}\}/gi, firstName)
      .replace(/\{\{investor_name\}\}/gi, investorName || '')
      .replace(/\{\{email\}\}/gi, investorEmail || '');
  };

  const cleanText = (text: string) => replacePlaceholders(stripHtml(text));

  const handleTemplateSelect = (templateId: string) => {
    setSelectedTemplateId(templateId);
    const template = templates?.find((t) => t.id === templateId);
    if (template) {
      setSubject(replacePlaceholders(template.subject));
      setBody(cleanText(template.body));
    }
  };

  const handleGenerateWithAI = async () => {
    setIsGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke('generate-email', {
        body: {
          investorId,
          templateId: selectedTemplateId || undefined,
          customInstructions: customInstructions || undefined,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setSubject(replacePlaceholders(data.subject || subject));
      setBody(cleanText(data.body || body));
      setAiReasoning(data.reasoning || '');

      // Auto-attach suggested documents
      if (data.suggested_documents?.length > 0) {
        const validIds = data.suggested_documents.filter((id: string) =>
          documents.some((d) => d.id === id)
        );
        setAttachedDocIds((prev) => [...new Set([...prev, ...validIds])]);
      }

      toast.success('Email generated by AI');
    } catch (error) {
      console.error('AI generation error:', error);
      toast.error('Failed to generate email', {
        description: error instanceof Error ? error.message : 'Please try again',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleAttachment = (docId: string) => {
    setAttachedDocIds((prev) =>
      prev.includes(docId) ? prev.filter((id) => id !== docId) : [...prev, docId]
    );
  };

  const handleSend = async () => {
    if (!to || !subject || !body) {
      toast.error('Please fill in all required fields');
      return;
    }

    // TODO: If scheduledTime is set, save as draft with scheduled_send_at
    // For now, send immediately
    if (scheduledTime) {
      toast.info('Email scheduled', {
        description: `Will be sent at ${format(new Date(scheduledTime), 'MMM d, yyyy h:mm a')}`,
      });
    }

    await sendEmail.mutateAsync({ to, subject, body });
    onOpenChange(false);
  };

  const attachedDocs = documents.filter((d) => attachedDocIds.includes(d.id));

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary" />
            Smart Compose
            {investorName && (
              <Badge variant="secondary" className="ml-2 font-normal">
                {investorName}
              </Badge>
            )}
          </DialogTitle>
        </DialogHeader>

        <ScrollArea className="flex-1 pr-4">
          <div className="space-y-4 pt-2">
            {/* AI Generation Section */}
            <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 space-y-3">
              <p className="text-sm font-medium flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                AI Email Generation
              </p>

              {templates && templates.length > 0 && (
                <div>
                  <Label className="text-xs text-muted-foreground">Base Template (optional)</Label>
                  <Select value={selectedTemplateId} onValueChange={handleTemplateSelect}>
                    <SelectTrigger className="mt-1">
                      <SelectValue placeholder="Select a template..." />
                    </SelectTrigger>
                    <SelectContent>
                      {templates.map((t) => (
                        <SelectItem key={t.id} value={t.id}>
                          {t.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              <div>
                <Label className="text-xs text-muted-foreground">
                  Custom Instructions (optional)
                </Label>
                <Input
                  placeholder="e.g., Focus on our Q4 traction, mention our SBA experience..."
                  value={customInstructions}
                  onChange={(e) => setCustomInstructions(e.target.value)}
                  className="mt-1"
                />
              </div>

              <Button
                onClick={handleGenerateWithAI}
                disabled={isGenerating}
                className="w-full"
                variant="outline"
              >
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <Sparkles className="w-4 h-4 mr-2" />
                )}
                {isGenerating ? 'Generating...' : 'Generate with AI'}
              </Button>

              {aiReasoning && (
                <p className="text-xs text-muted-foreground italic border-l-2 border-primary/30 pl-2">
                  {aiReasoning}
                </p>
              )}
            </div>

            {/* Email Fields */}
            <div>
              <Label htmlFor="to">To</Label>
              <Input
                id="to"
                type="email"
                placeholder="recipient@example.com"
                value={to}
                onChange={(e) => setTo(e.target.value)}
              />
            </div>

            <div>
              <Label htmlFor="subject">Subject</Label>
              <Input
                id="subject"
                placeholder="Email subject"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
              />
            </div>

            <div>
              <Label htmlFor="body">Message</Label>
              <Textarea
                id="body"
                placeholder="Write your message or generate with AI..."
                className="min-h-[180px]"
                value={body}
                onChange={(e) => setBody(e.target.value)}
              />
            </div>

            {/* Schedule Send */}
            <div>
              <Label className="flex items-center gap-2">
                <CalendarClock className="w-4 h-4" />
                Schedule Send (optional)
              </Label>
              <Input
                type="datetime-local"
                value={scheduledTime}
                onChange={(e) => setScheduledTime(e.target.value)}
                className="mt-1"
                min={format(new Date(), "yyyy-MM-dd'T'HH:mm")}
              />
              {scheduledTime && (
                <div className="flex items-center gap-2 mt-1">
                  <Badge variant="secondary" className="text-xs">
                    <Clock className="w-3 h-3 mr-1" />
                    {format(new Date(scheduledTime), 'MMM d, yyyy h:mm a')}
                  </Badge>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-5 w-5"
                    onClick={() => setScheduledTime('')}
                  >
                    <X className="w-3 h-3" />
                  </Button>
                </div>
              )}
            </div>

            {/* Document Attachments */}
            <div>
              <Label className="flex items-center gap-2">
                <Paperclip className="w-4 h-4" />
                Attachments
              </Label>

              {(attachedDocs.length > 0 || manualFiles.length > 0) && (
                <div className="flex flex-wrap gap-2 mt-2">
                  {attachedDocs.map((doc) => (
                    <Badge
                      key={doc.id}
                      variant="secondary"
                      className="flex items-center gap-1 pr-1"
                    >
                      <FileText className="w-3 h-3" />
                      <span className="text-xs max-w-[150px] truncate">{doc.name}</span>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-4 w-4 ml-1 hover:bg-destructive/20"
                        onClick={() => toggleAttachment(doc.id)}
                      >
                        <X className="w-3 h-3" />
                      </Button>
                    </Badge>
                  ))}
                  {manualFiles.map((file, idx) => (
                    <Badge
                      key={`manual-${idx}`}
                      variant="secondary"
                      className="flex items-center gap-1 pr-1"
                    >
                      <Upload className="w-3 h-3" />
                      <span className="text-xs max-w-[150px] truncate">{file.name}</span>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-4 w-4 ml-1 hover:bg-destructive/20"
                        onClick={() => setManualFiles((prev) => prev.filter((_, i) => i !== idx))}
                      >
                        <X className="w-3 h-3" />
                      </Button>
                    </Badge>
                  ))}
                </div>
              )}

              <div className="flex gap-2 mt-2">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => fileInputRef.current?.click()}
                  className="gap-1"
                >
                  <Upload className="w-3.5 h-3.5" />
                  Upload File
                </Button>
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  className="hidden"
                  onChange={(e) => {
                    if (e.target.files) {
                      setManualFiles((prev) => [...prev, ...Array.from(e.target.files!)]);
                    }
                    e.target.value = '';
                  }}
                />
              </div>

              {documents.length > 0 && (
                <div className="mt-2 max-h-[120px] overflow-y-auto border rounded-md">
                  {documents
                    .filter((d) => !attachedDocIds.includes(d.id))
                    .map((doc) => (
                      <button
                        key={doc.id}
                        onClick={() => toggleAttachment(doc.id)}
                        className="w-full text-left px-3 py-2 text-sm hover:bg-accent/50 flex items-center gap-2 border-b last:border-b-0"
                      >
                        <FileText className="w-3.5 h-3.5 text-muted-foreground shrink-0" />
                        <span className="truncate">{doc.name}</span>
                        <Badge variant="outline" className="text-[10px] ml-auto shrink-0">
                          {doc.document_type}
                        </Badge>
                      </button>
                    ))}
                </div>
              )}
            </div>
          </div>
        </ScrollArea>

        {/* Actions */}
        <div className="flex justify-end gap-2 pt-4 border-t">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            onClick={handleSend}
            disabled={!to || !subject || !body || sendEmail.isPending}
          >
            {sendEmail.isPending ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : scheduledTime ? (
              <Clock className="w-4 h-4 mr-2" />
            ) : (
              <Send className="w-4 h-4 mr-2" />
            )}
            {scheduledTime ? 'Schedule' : 'Send'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
